#spring:
#  shardingsphere:
#    datasource:
#      names: ds0,ds1
#      ds0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://192.168.153.128:3306/ds0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: root
#      ds1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://192.168.153.128:3306/ds1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: root
#    sharding:
#      default-database-strategy:
#        inline:
#          sharding-column: user_id
#          algorithm-expression: ds$->{user_id % 2}
#      binding-tables: health_record,health_task
#      broadcast-tables: health_level
#      tables:
#        health_record:
#          actual-data-nodes: ds$->{0..1}.health_record
#          key-generator:
#            column: record_id
#            type: SNOWFLAKE
#            props:
#              worker:
#                id: 33
#        health_task:
#          actual-data-nodes: ds$->{0..1}.health_task
#          key-generator:
#            column: task_id
#            type: SNOWFLAKE
#            props:
#              worker:
#                id: 33
#      default-data-source-name: ds0
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.chenhl.shardingjdbcdemo.domain
#  configuration:
#    map-underscore-to-camel-case: true
#
#server:
#  port: 8080
#  tomcat:
#    uri-encoding: UTF-8
#  servlet:
#    encoding:
#      charset: UTF-8
#      force: true